version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      TWITTER_OAUTH2_CLIENT_ID: ${TWITTER_OAUTH2_CLIENT_ID}
      TWITTER_OAUTH2_CLIENT_SECRET: ${TWITTER_OAUTH2_CLIENT_SECRET}
      TWITTER_CONSUMER_KEYS_API_KEY: ${TWITTER_CONSUMER_KEYS_API_KEY}
      TWITTER_CONSUMER_KEYS_API_KEY_SECRET: ${TWITTER_CONSUMER_KEYS_API_KEY_SECRET}
      # Specify only in local environment to ensure that oauth callback URL does not error even with http.
      OAUTHLIB_INSECURE_TRANSPORT: True
    command: poetry run flask --app main.py --debug run --host=0.0.0.0 --port 8000
