version: "3"
services:
  app:
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    environment:
      TWITTER_APP_CLIENT_ID: ${TWITTER_APP_CLIENT_ID}
      TWITTER_APP_CLIENT_SECRET: ${TWITTER_APP_CLIENT_SECRET}
    command: poetry run flask --app main.py --debug run --host=0.0.0.0 --port 8000
